# DB_NAME=${MYSQL_DATABASE}
# DB_USER=${MYSQL_USER}
# DB_PASSWORD=${MYSQL_PASSWORD}
# DB_HOST=${MYSQL_HOST}

WP_ENV=production
WP_HOME=http://${HOSTNAME}
WP_SITEURL=${WP_HOME}

AUTH_KEY=generateme
SECURE_AUTH_KEY=generateme
LOGGED_IN_KEY=generateme
NONCE_KEY=generateme
AUTH_SALT=generateme
SECURE_AUTH_SALT=generateme
LOGGED_IN_SALT=generateme
NONCE_SALT=generateme
